- name: Schedule log_stats.py via cron
  hosts: appserv
  become: yes
  tasks:
    - name: Install cron package
      package:
        name: cron
        state: present

    - name: Add cron job
      cron:
        name: "Run log_stats.py every 5 minutes"
        minute: "*/5"
        job: /usr/bin/python3/var/lib/mysql/syslogs
        user: ubuntu
...