---
- name: Install and Configure Jenkins
  hosts: jenkinserv
  become: yes
  roles:
    - jenkins

- name: Provision Jenkins Agent on AWS
  hosts: jenkinserv
  become: false
  roles:
    - jenkins_agent

- name: Install and Configure MySQL Server
  hosts: mysqlserv
  become: yes
  roles:
    - mysql

- name: Configure Python App Server
  hosts: appserv
  become: yes
  roles:
    - python
...



