---
- name: Install Python and Deploy Logging Script
  hosts: appserv
  become: yes
  tasks:
    - name: Install Python and dependencies
      apt:
        name: python3
        state: present
    - name: Install required Python libraries
      pip:
        name:
        - psutil==5.9.0
        - mysql-connector-python==8.0.32
        executable: pip3
    - name: Ensure the destination directory exists
      file:
        path: /var/www/html
        state: directory
    - name: Copy Python logging script
      copy:
        src: /home/ec2-user/Auto-provison/log_stats.py
        dest: /var/www/html/log_stats.py
