---
- name: Install Python and Deploy Logging Script
  hosts: appserv
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install required Python libraries
      ansible.builtin.pip:
        name:
          - psutil==5.9.0
          - mysql-connector-python==8.0.32
        executable: pip3
      extra_args: --break-system-packages

    - name: Ensure the destination directory exists
      file:
        path: /var/www/html
        state: directory

    - name: Copy Python logging script
      copy:
        src: /home/ec2-user/Auto-provison/log_stats.py
        dest: /var/www/html/log_stats.py
