- name: Install Python and Deploy Logging Script
  hosts: all
  become: yes
  
  tasks:
    - name: Install Python and dependencies
      yum:
        name: python3
        state: present

    - name: Install required Python libraries
      pip:
         name:
          - mysql-connector-python
          - psutil
        executable: pip3

    - name: Ensure the destination directory exists
      file:
        path: /var/www/html
        state: directory

    - name: Copy Python logging script
      copy:
        src: ./scripts/log_stats.py  # Ensure this exists on your Ansible control node
        dest: /var/www/html/log_stats.py
...
