---
- name: Install MySQL and Configure Database
  hosts: mqsql
  become: yes
  
  tasks:
    - name: Install mariadb105-server
      yum:
        name: mariadb-server
        state: present
    - name: Start and enable mariadb105-server
      systemd:
        name: mariadb
        state: started
        enabled: yes
    - name: Ensure MySQL is running
      service:
        name: mariadb
        state: started
    - name: Create MySQL database and user
      mysql_db:
        name: syslogs
        state: present
    - name: Create MySQL user and grant privileges
      mysql_user:
        name: devops
        password: password
        priv: syslogs.*:ALL
        state: present
    - name: Flush privileges
      mysql_user:
        name: devops
        state: reloaded
...