- name: Install MySQL and Configure Database
  hosts: M1
  become: yes

  tasks:
    - name: Update package cache (dnf)
      dnf:
        update_cache: yes
      when: ansible_pkg_mgr == 'dnf'

    - name: Install MariaDB Server (Amazon Linux 2023)
      dnf:
        name:
          - mariadb105
          - mariadb105-server
        state: present
      when: ansible_distribution == 'Amazon' and ansible_distribution_major_version == "2023"

    - name: Install MariaDB Server (Other distributions)
      package:
        name: mariadb-server
        state: present
      when: ansible_distribution != 'Amazon' or (ansible_distribution == 'Amazon' and ansible_distribution_major_version != "2023")

    - name: Install pip3 for Python 3
      dnf:
        name: python3-pip
        state: present

    - name: Install PyMySQL using pip3
      pip:
        name: PyMySQL
        executable: pip3

    - name: Set Python interpreter for MySQL modules
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

    - name: Start and enable MariaDB service
      systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Ensure MySQL is running
      service:
        name: mariadb
        state: started

    - name: Create MySQL database
      community.mysql.mysql_db:
        name: "{{ db_name | default('syslogs') }}"
        state: present
      ignore_errors: yes

    - name: Create MySQL user and grant privileges
      community.mysql.mysql_user:
        name: "{{ db_user | default('devops') }}"
        password: "{{ db_pass | default('password') }}"
        priv: "{{ db_name | default('syslogs') }}.*:ALL"
        state: present
        login_user: root
        login_password: admin123
        login_host: localhost

    - name: Flush privileges
      community.mysql.mysql_user:
        name: "{{ db_user | default('devops') }}"
        state: reloaded

    - name: Copy init_db.sql script
      copy:
        src: init_db.sql
        dest: /tmp/init_db.sql

    - name: Execute init_db.sql script
      shell: "mysql -u {{ db_user | default('devops') }} -p{{ db_pass | default('password') }} {{ db_name | default('syslogs') }} < /tmp/init_db.sql"
      args:
        executable: /bin/bash
