---
- name: Install MySQL and Configure Database
  hosts: M1
  become: yes

  tasks:
    - name: Enable MariaDB Repository (Amazon Linux Only)
      command: amazon-linux-extras enable mariadb10.5
      when: ansible_distribution == "Amazon"

    - name: Update package cache (yum)
      yum:
        update_cache: yes
      when: ansible_pkg_mgr == 'yum'

    - name: Update package cache (dnf)
      dnf:
        update_cache: yes
      when: ansible_pkg_mgr == 'dnf'

    - name: Install MariaDB Server
      package:
        name: mariadb-server
        state: present

    - name: Install MySQL Python dependencies
      package:
        name: python3-PyMySQL
        state: present

    - name: Start and enable MariaDB service
      systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Ensure MySQL is running
      service:
        name: mariadb
        state: started

    - name: Create MySQL database
      mysql_db:
        name: "{{ db_name | default('syslogs') }}"
        state: present
      environment:
        MYSQL_PWD: "{{ db_pass | default('password') }}"

    - name: Create MySQL user and grant privileges
      mysql_user:
        name: "{{ db_user | default('devops') }}"
        password: "{{ db_pass | default('password') }}"
        priv: "{{ db_name | default('syslogs') }}.*:ALL"
        host: "%"
        state: present
      environment:
        MYSQL_PWD: "{{ db_pass | default('password') }}"

    - name: Flush privileges
      mysql_query:
        login_user: root
        login_password: "{{ db_pass | default('password') }}"
        query: "FLUSH PRIVILEGES;"
        db: "{{ db_name | default('syslogs') }}"

    - name: Copy init_db.sql script
      copy:
        src: init_db.sql
        dest: /tmp/init_db.sql

    - name: Execute init_db.sql script
      shell: "mysql -u {{ db_user | default('devops') }} -p{{ db_pass | default('password') }} {{ db_name | default('syslogs') }} < /tmp/init_db.sql"
...